// Core shared types used across the whole app and by every module.

export type ModuleId = "fitness" | "student" | "finance" | string;

/**
 * A generic task. Tasks can be created manually by the user, or generated
 * automatically by a module (e.g. "Today's run" from the fitness module).
 */
export interface Task {
  id: string;
  userId: string;
  title: string;
  done: boolean;
  dueDate: string | null; // ISO date string, e.g. "2026-06-29"
  module: ModuleId | null; // null = general/manual task, not tied to a module
  source: "manual" | "auto"; // manual = user-added, auto = generated by a module
  sourceRef: string | null; // optional reference id back to the module's own record
  createdAt: string;
}

/**
 * A generic event on the calendar. Used for things like runs, hikes, exams,
 * deadlines, outings -- anything that has a date (and optionally a time).
 */
export interface CalendarEvent {
  id: string;
  userId: string;
  title: string;
  module: ModuleId | null;
  type: string; // free-form per module, e.g. "run" | "hike" | "exam" | "deadline"
  date: string; // ISO date string
  time: string | null; // optional ISO time string, e.g. "06:30"
  details: Record<string, unknown>; // flexible per-module payload
  createdAt: string;
}

/**
 * Every module registers one of these. The dashboard and nav bar are built
 * by iterating over the list of registered modules -- so adding a new
 * module later means writing a new folder + one of these, not touching
 * dashboard code.
 */
export interface ModuleDefinition {
  id: ModuleId;
  label: string; // shown in nav, e.g. "Fitness"
  icon: string; // tabler icon name, e.g. "run"
  route: string; // e.g. "/fitness"
  color: "teal" | "coral" | "purple" | "amber" | "blue" | "pink"; // accent used for this module's UI bits

  /** Returns today's auto-generated task(s) for this module, if any. */
  getTodayTasks: (userId: string) => Promise<Task[]>;

  /** Returns a short summary payload to render on the dashboard card. */
  getDashboardSummary: (userId: string) => Promise<DashboardSummary>;
}

/**
 * Generic shape returned by each module for its dashboard card.
 * `data` is intentionally loose -- the matching dashboard card component
 * for that module knows how to render its own shape.
 */
export interface DashboardSummary {
  module: ModuleId;
  headline: string; // e.g. "3 workouts this week"
  data: unknown;
}
